#pragma once

template <class T>
class CProxy_IShapeEvents : public IConnectionPointImpl<T, &__uuidof( _IShapeEvents ), CComDynamicUnkArray>
{
	//Warning this class will  be regenerated by the wizard.
public:
};
